- name: Clear bash settings
  file:
    state: absent
    dest: "{{ remote_home}}/bashrc.d"
- name: Copy bash settings
  copy:
    src: "{{ config_root }}/bashrc.d"
    dest: "{{ remote_home }}"
- name: Overwrite main .bashrc
  copy:
    src: "{{ config_root }}/.bashrc"
    dest: "{{ remote_home }}"

