- name: Remove VIM all settings
  file:
    path: "{{ config_root }}/.vim"
    state: absent
- name: color template - thanks for nanotech/jellybeans
  copy:
    src: "{{ config_root }}/.vim/colors"
    dest: "{{ remote_home }}/.vim"
- name: vimrc
  copy:
    src: "{{ config_root }}/.vimrc"
    dest: "{{ remote_home }}"
- name: Install Vundle.vim
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "{{ remote_home }}/.vim/bundle/Vundle.vim"
- name: Install vim plugins
  shell: vim +PluginInstall +qall 2> /dev/null
