- name: color template - thanks for nanotech/jellybeans
  copy:
    src: "{{ config_root }}/.vim"
    dest: "{{ remote_home }}"
- name: vimrc
  copy:
    src: "{{ config_root }}/.vimrc"
    dest: "{{ remote_home }}"
